language: node_js
node_js:
  - stable

branches:
  only:
    - master

script:
  - npm run build

notifications:
  email:
    recipients:
      - khjzzm@gmail.com

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: kimzzang-frontend
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    local_dir: build
    on:
      repo: khjzzm/kimzzang-frontend #Github 주소
      branch: master