language: node_js
node_js:
  - stable

branches:
  only:
    - master

script:
  - npm run build

notifications:
  email:
    recipients:
      - khjzzm@gmail.com
  slack:
    rooms:
      - khjzzm:1RHNb42loKQ11FTaVUAWaoHt#noti
    on_success: always  # change: send a notification when the build status changes.
    on_failure: always  # always: always send a notification.
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: kimzzang-frontend-bucket
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    local_dir: build
    on:
      repo: khjzzm/kimzzang-frontend #Github 주소
      branch: master